name: Test FEEL expressions

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  jbang-drools-stable:
    runs-on: ubuntu-latest
    name: Testing with Drools latest stable release
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: /root/.jbang
        key: $-jbang-$
        restore-keys: |
            $-jbang-
    - name: jbang
      uses: jbangdev/jbang-action@v0.111.0
      with:
        script: test.java
  jbang-drools-snapshot:
    runs-on: ubuntu-latest
    name: Testing with Drools latest SNAPSHOT release
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: /root/.jbang
          key: $-jbang-$
          restore-keys: |
            $-jbang-
      - name: jbang
        uses: jbangdev/jbang-action@v0.111.0
        with:
          script: test.java
          jbangargs: -Ddrools.version=999-SNAPSHOT
